[package]
name = "gb_emu"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
winit = "0.28"
pixels = "0.13"
log = "0.4"
env_logger = "0.11"
